// Generated by scripts/gen_jni_hooks.py
// Do not edit manually.

use core::ffi::c_void;
use crate::jni_env::{jclass, jint, jlong, jboolean};
use crate::hook_context::HookContext;

#[repr(C)]
pub struct AppSpecializeArgs {
    pub uid: *mut c_void,
    pub gid: *mut c_void,
    pub gids: *mut c_void,
    pub runtime_flags: *mut c_void,
    pub rlimits: *mut c_void,
    pub mount_external: *mut c_void,
    pub se_info: *mut c_void,
    pub se_name: *mut c_void,
    pub nice_name: *mut c_void,
    pub managed_nice_name: *mut c_void,
    pub instruction_set: *mut c_void,
    pub app_data_dir: *mut c_void,
    pub fds_to_close: *mut c_void,
    pub fds_to_ignore: *mut c_void,
    pub is_child_zygote: *mut c_void,
    pub is_top_app: *mut c_void,
    pub pkg_data_info_list: *mut c_void,
    pub whitelisted_data_info_list: *mut c_void,
    pub mount_data_dirs: *mut c_void,
    pub mount_storage_dirs: *mut c_void,
    pub mount_sysprop_overrides: *mut c_void,
}

#[repr(C)]
pub struct ServerSpecializeArgs {
    pub uid: *mut c_void,
    pub gid: *mut c_void,
    pub gids: *mut c_void,
    pub runtime_flags: *mut c_void,
    pub rlimits: *mut c_void,
    pub permitted_capabilities: *mut c_void,
    pub effective_capabilities: *mut c_void,
}

pub struct JniMethodEntry {
    pub name: &'static str,
    pub sig: &'static str,
    pub orig_idx: usize,
    pub handler: *mut c_void,
}

pub const TABLE_SIZE: usize = 19;

pub static ORIG_PTRS: core::cell::UnsafeCell<[*mut c_void; TABLE_SIZE]> =
    core::cell::UnsafeCell::new([core::ptr::null_mut(); TABLE_SIZE]);

pub fn set_orig_ptr(i: usize, ptr: *mut c_void) {
    unsafe { (*ORIG_PTRS.get())[i] = ptr; }
}

pub fn get_orig_ptr(i: usize) -> *mut c_void {
    unsafe { (*ORIG_PTRS.get())[i] }
}

pub static JNI_METHOD_TABLE: [JniMethodEntry; TABLE_SIZE] = [
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[ILjava/lang/String;Ljava/lang/String;)I",
        orig_idx: 0,
        handler: nativeForkAndSpecialize_l as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[I[ILjava/lang/String;Ljava/lang/String;)I",
        orig_idx: 1,
        handler: nativeForkAndSpecialize_o as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I",
        orig_idx: 2,
        handler: nativeForkAndSpecialize_p as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z)I",
        orig_idx: 3,
        handler: nativeForkAndSpecialize_q_alt as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ)I",
        orig_idx: 4,
        handler: nativeForkAndSpecialize_r as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)I",
        orig_idx: 5,
        handler: nativeForkAndSpecialize_u as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;IILjava/lang/String;[ILjava/lang/String;Ljava/lang/String;)I",
        orig_idx: 6,
        handler: nativeForkAndSpecialize_samsung_m as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;IILjava/lang/String;[ILjava/lang/String;Ljava/lang/String;I)I",
        orig_idx: 7,
        handler: nativeForkAndSpecialize_samsung_n as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;IILjava/lang/String;[I[ILjava/lang/String;Ljava/lang/String;)I",
        orig_idx: 8,
        handler: nativeForkAndSpecialize_samsung_o as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I",
        orig_idx: 9,
        handler: nativeForkAndSpecialize_samsung_p as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkAndSpecialize",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ[J)I",
        orig_idx: 10,
        handler: nativeForkAndSpecialize_grapheneos_u as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeSpecializeAppProcess",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;)V",
        orig_idx: 11,
        handler: nativeSpecializeAppProcess_q as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeSpecializeAppProcess",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z)V",
        orig_idx: 12,
        handler: nativeSpecializeAppProcess_q_alt as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeSpecializeAppProcess",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZ)V",
        orig_idx: 13,
        handler: nativeSpecializeAppProcess_r as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeSpecializeAppProcess",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ)V",
        orig_idx: 14,
        handler: nativeSpecializeAppProcess_u as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeSpecializeAppProcess",
        sig: "(II[II[[IILjava/lang/String;IILjava/lang/String;ZLjava/lang/String;Ljava/lang/String;)V",
        orig_idx: 15,
        handler: nativeSpecializeAppProcess_samsung_q as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeSpecializeAppProcess",
        sig: "(II[II[[IILjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;ZZZ[J)V",
        orig_idx: 16,
        handler: nativeSpecializeAppProcess_grapheneos_u as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkSystemServer",
        sig: "(II[II[[IJJ)I",
        orig_idx: 17,
        handler: nativeForkSystemServer_l as *mut c_void,
    },
    JniMethodEntry {
        name: "nativeForkSystemServer",
        sig: "(II[IIII[[IJJ)I",
        orig_idx: 18,
        handler: nativeForkSystemServer_samsung_q as *mut c_void,
    },
];

pub unsafe fn hook_and_save_zygote_methods(
    env: *mut c_void,
    methods: *mut crate::jni_env::JNINativeMethod,
    n_methods: jint,
) {
    if methods.is_null() || n_methods <= 0 { return; }
    for i in 0..n_methods as isize {
        let m = &mut *methods.offset(i);
        let m_name = core::ffi::CStr::from_ptr(m.name).to_str().unwrap_or("");
        let m_sig = core::ffi::CStr::from_ptr(m.signature).to_str().unwrap_or("");
        for entry in JNI_METHOD_TABLE {
            if entry.name == m_name && entry.sig == m_sig {
                set_orig_ptr(entry.orig_idx, m.fn_ptr);
                m.fn_ptr = entry.handler;
                break;
            }
        }
    }
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_l(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> jint {
    let orig = get_orig_ptr(0);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::null_mut(),
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, instruction_set, app_data_dir);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_o(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> jint {
    let orig = get_orig_ptr(1);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::null_mut(),
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, fds_to_ignore, instruction_set, app_data_dir);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_p(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> jint {
    let orig = get_orig_ptr(2);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, fds_to_ignore, is_child_zygote, instruction_set, app_data_dir);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_q_alt(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean
) -> jint {
    let orig = get_orig_ptr(3);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, fds_to_ignore, is_child_zygote, instruction_set, app_data_dir, is_top_app);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_r(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean
) -> jint {
    let orig = get_orig_ptr(4);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::addr_of_mut!(pkg_data_info_list) as *mut c_void,
        whitelisted_data_info_list: core::ptr::addr_of_mut!(whitelisted_data_info_list) as *mut c_void,
        mount_data_dirs: core::ptr::addr_of_mut!(mount_data_dirs) as *mut c_void,
        mount_storage_dirs: core::ptr::addr_of_mut!(mount_storage_dirs) as *mut c_void,
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, fds_to_ignore, is_child_zygote, instruction_set, app_data_dir, is_top_app, pkg_data_info_list, whitelisted_data_info_list, mount_data_dirs, mount_storage_dirs);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_u(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean
) -> jint {
    let orig = get_orig_ptr(5);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::addr_of_mut!(pkg_data_info_list) as *mut c_void,
        whitelisted_data_info_list: core::ptr::addr_of_mut!(whitelisted_data_info_list) as *mut c_void,
        mount_data_dirs: core::ptr::addr_of_mut!(mount_data_dirs) as *mut c_void,
        mount_storage_dirs: core::ptr::addr_of_mut!(mount_storage_dirs) as *mut c_void,
        mount_sysprop_overrides: core::ptr::addr_of_mut!(mount_sysprop_overrides) as *mut c_void,
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, fds_to_ignore, is_child_zygote, instruction_set, app_data_dir, is_top_app, pkg_data_info_list, whitelisted_data_info_list, mount_data_dirs, mount_storage_dirs, mount_sysprop_overrides);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_samsung_m(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _0: jint, _1: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> jint {
    let orig = get_orig_ptr(6);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _0: jint, _1: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::null_mut(),
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, _0, _1, nice_name, fds_to_close, instruction_set, app_data_dir);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_samsung_n(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _2: jint, _3: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void, _4: jint
) -> jint {
    let orig = get_orig_ptr(7);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _2: jint, _3: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void, _4: jint) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::null_mut(),
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, _2, _3, nice_name, fds_to_close, instruction_set, app_data_dir, _4);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_samsung_o(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _5: jint, _6: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> jint {
    let orig = get_orig_ptr(8);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _5: jint, _6: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::null_mut(),
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, _5, _6, nice_name, fds_to_close, fds_to_ignore, instruction_set, app_data_dir);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_samsung_p(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _7: jint, _8: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> jint {
    let orig = get_orig_ptr(9);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _7: jint, _8: jint, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, _7, _8, nice_name, fds_to_close, fds_to_ignore, is_child_zygote, instruction_set, app_data_dir);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkAndSpecialize_grapheneos_u(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean, _9: *mut c_void
) -> jint {
    let orig = get_orig_ptr(10);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, fds_to_close: *mut c_void, fds_to_ignore: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean, _9: *mut c_void) -> jint
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::addr_of_mut!(fds_to_close) as *mut c_void,
        fds_to_ignore: core::ptr::addr_of_mut!(fds_to_ignore) as *mut c_void,
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::addr_of_mut!(pkg_data_info_list) as *mut c_void,
        whitelisted_data_info_list: core::ptr::addr_of_mut!(whitelisted_data_info_list) as *mut c_void,
        mount_data_dirs: core::ptr::addr_of_mut!(mount_data_dirs) as *mut c_void,
        mount_storage_dirs: core::ptr::addr_of_mut!(mount_storage_dirs) as *mut c_void,
        mount_sysprop_overrides: core::ptr::addr_of_mut!(mount_sysprop_overrides) as *mut c_void,
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeForkAndSpecialize_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, fds_to_close, fds_to_ignore, is_child_zygote, instruction_set, app_data_dir, is_top_app, pkg_data_info_list, whitelisted_data_info_list, mount_data_dirs, mount_storage_dirs, mount_sysprop_overrides, _9);
    if _ret == 0 {
        ctx.native_specialize_app_process_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.app_specialize_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeSpecializeAppProcess_q(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> () {
    let orig = get_orig_ptr(11);
    if orig.is_null() { return; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> ()
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::null_mut(),
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeSpecializeAppProcess_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, is_child_zygote, instruction_set, app_data_dir);
    ctx.native_specialize_app_process_post();
    crate::hook_context::set_current_ptr(_prev_ctx);
}

#[no_mangle]
pub unsafe extern "C" fn nativeSpecializeAppProcess_q_alt(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean
) -> () {
    let orig = get_orig_ptr(12);
    if orig.is_null() { return; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean) -> ()
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::null_mut(),
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeSpecializeAppProcess_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, is_child_zygote, instruction_set, app_data_dir, is_top_app);
    ctx.native_specialize_app_process_post();
    crate::hook_context::set_current_ptr(_prev_ctx);
}

#[no_mangle]
pub unsafe extern "C" fn nativeSpecializeAppProcess_r(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean
) -> () {
    let orig = get_orig_ptr(13);
    if orig.is_null() { return; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean) -> ()
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::null_mut(),
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::addr_of_mut!(pkg_data_info_list) as *mut c_void,
        whitelisted_data_info_list: core::ptr::addr_of_mut!(whitelisted_data_info_list) as *mut c_void,
        mount_data_dirs: core::ptr::addr_of_mut!(mount_data_dirs) as *mut c_void,
        mount_storage_dirs: core::ptr::addr_of_mut!(mount_storage_dirs) as *mut c_void,
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeSpecializeAppProcess_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, is_child_zygote, instruction_set, app_data_dir, is_top_app, pkg_data_info_list, whitelisted_data_info_list, mount_data_dirs, mount_storage_dirs);
    ctx.native_specialize_app_process_post();
    crate::hook_context::set_current_ptr(_prev_ctx);
}

#[no_mangle]
pub unsafe extern "C" fn nativeSpecializeAppProcess_u(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean
) -> () {
    let orig = get_orig_ptr(14);
    if orig.is_null() { return; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean) -> ()
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::null_mut(),
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::addr_of_mut!(pkg_data_info_list) as *mut c_void,
        whitelisted_data_info_list: core::ptr::addr_of_mut!(whitelisted_data_info_list) as *mut c_void,
        mount_data_dirs: core::ptr::addr_of_mut!(mount_data_dirs) as *mut c_void,
        mount_storage_dirs: core::ptr::addr_of_mut!(mount_storage_dirs) as *mut c_void,
        mount_sysprop_overrides: core::ptr::addr_of_mut!(mount_sysprop_overrides) as *mut c_void,
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeSpecializeAppProcess_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, is_child_zygote, instruction_set, app_data_dir, is_top_app, pkg_data_info_list, whitelisted_data_info_list, mount_data_dirs, mount_storage_dirs, mount_sysprop_overrides);
    ctx.native_specialize_app_process_post();
    crate::hook_context::set_current_ptr(_prev_ctx);
}

#[no_mangle]
pub unsafe extern "C" fn nativeSpecializeAppProcess_samsung_q(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _10: jint, _11: jint, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void
) -> () {
    let orig = get_orig_ptr(15);
    if orig.is_null() { return; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, _10: jint, _11: jint, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void) -> ()
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::null_mut(),
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::null_mut(),
        pkg_data_info_list: core::ptr::null_mut(),
        whitelisted_data_info_list: core::ptr::null_mut(),
        mount_data_dirs: core::ptr::null_mut(),
        mount_storage_dirs: core::ptr::null_mut(),
        mount_sysprop_overrides: core::ptr::null_mut(),
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeSpecializeAppProcess_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, _10, _11, nice_name, is_child_zygote, instruction_set, app_data_dir);
    ctx.native_specialize_app_process_post();
    crate::hook_context::set_current_ptr(_prev_ctx);
}

#[no_mangle]
pub unsafe extern "C" fn nativeSpecializeAppProcess_grapheneos_u(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean, _12: *mut c_void
) -> () {
    let orig = get_orig_ptr(16);
    if orig.is_null() { return; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, mount_external: jint, se_info: *mut c_void, nice_name: *mut c_void, is_child_zygote: jboolean, instruction_set: *mut c_void, app_data_dir: *mut c_void, is_top_app: jboolean, pkg_data_info_list: *mut c_void, whitelisted_data_info_list: *mut c_void, mount_data_dirs: jboolean, mount_storage_dirs: jboolean, mount_sysprop_overrides: jboolean, _12: *mut c_void) -> ()
        = core::mem::transmute(orig);
    let mut args = AppSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        mount_external: core::ptr::addr_of_mut!(mount_external) as *mut c_void,
        se_info: core::ptr::addr_of_mut!(se_info) as *mut c_void,
        se_name: core::ptr::null_mut(),
        nice_name: core::ptr::addr_of_mut!(nice_name) as *mut c_void,
        managed_nice_name: core::ptr::null_mut(),
        instruction_set: core::ptr::addr_of_mut!(instruction_set) as *mut c_void,
        app_data_dir: core::ptr::addr_of_mut!(app_data_dir) as *mut c_void,
        fds_to_close: core::ptr::null_mut(),
        fds_to_ignore: core::ptr::null_mut(),
        is_child_zygote: core::ptr::addr_of_mut!(is_child_zygote) as *mut c_void,
        is_top_app: core::ptr::addr_of_mut!(is_top_app) as *mut c_void,
        pkg_data_info_list: core::ptr::addr_of_mut!(pkg_data_info_list) as *mut c_void,
        whitelisted_data_info_list: core::ptr::addr_of_mut!(whitelisted_data_info_list) as *mut c_void,
        mount_data_dirs: core::ptr::addr_of_mut!(mount_data_dirs) as *mut c_void,
        mount_storage_dirs: core::ptr::addr_of_mut!(mount_storage_dirs) as *mut c_void,
        mount_sysprop_overrides: core::ptr::addr_of_mut!(mount_sysprop_overrides) as *mut c_void,
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.nativeSpecializeAppProcess_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, mount_external, se_info, nice_name, is_child_zygote, instruction_set, app_data_dir, is_top_app, pkg_data_info_list, whitelisted_data_info_list, mount_data_dirs, mount_storage_dirs, mount_sysprop_overrides, _12);
    ctx.native_specialize_app_process_post();
    crate::hook_context::set_current_ptr(_prev_ctx);
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkSystemServer_l(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, permitted_capabilities: jlong, effective_capabilities: jlong
) -> jint {
    let orig = get_orig_ptr(17);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, rlimits: *mut c_void, permitted_capabilities: jlong, effective_capabilities: jlong) -> jint
        = core::mem::transmute(orig);
    let mut args = ServerSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        permitted_capabilities: core::ptr::addr_of_mut!(permitted_capabilities) as *mut c_void,
        effective_capabilities: core::ptr::addr_of_mut!(effective_capabilities) as *mut c_void,
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.native_fork_system_server_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, rlimits, permitted_capabilities, effective_capabilities);
    if _ret == 0 {
        ctx.server_specialize_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.fork_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

#[no_mangle]
pub unsafe extern "C" fn nativeForkSystemServer_samsung_q(
    env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, _13: jint, _14: jint, rlimits: *mut c_void, permitted_capabilities: jlong, effective_capabilities: jlong
) -> jint {
    let orig = get_orig_ptr(18);
    if orig.is_null() { return -1; }
    let orig_fn: unsafe extern "C" fn(env: *mut c_void, clazz: jclass, uid: jint, gid: jint, gids: *mut c_void, runtime_flags: jint, _13: jint, _14: jint, rlimits: *mut c_void, permitted_capabilities: jlong, effective_capabilities: jlong) -> jint
        = core::mem::transmute(orig);
    let mut args = ServerSpecializeArgs {
        uid: core::ptr::addr_of_mut!(uid) as *mut c_void,
        gid: core::ptr::addr_of_mut!(gid) as *mut c_void,
        gids: core::ptr::addr_of_mut!(gids) as *mut c_void,
        runtime_flags: core::ptr::addr_of_mut!(runtime_flags) as *mut c_void,
        rlimits: core::ptr::addr_of_mut!(rlimits) as *mut c_void,
        permitted_capabilities: core::ptr::addr_of_mut!(permitted_capabilities) as *mut c_void,
        effective_capabilities: core::ptr::addr_of_mut!(effective_capabilities) as *mut c_void,
    };
    let mut ctx = HookContext::new(env, core::ptr::addr_of_mut!(args) as *mut c_void, "com.android.internal.os.Zygote");
    let _prev_ctx = crate::hook_context::get_current_ptr();
    crate::hook_context::set_current(&mut ctx);
    ctx.native_fork_system_server_pre();
    let _ret = orig_fn(env, clazz, uid, gid, gids, runtime_flags, _13, _14, rlimits, permitted_capabilities, effective_capabilities);
    if _ret == 0 {
        ctx.server_specialize_post();
        crate::unload::SHOULD_UNLOAD.store(true, Ordering::Release);
    } else {
        ctx.fork_post();
    }
    crate::hook_context::set_current_ptr(_prev_ctx);
    _ret
}

